### ISSUE TITLE
Error: The request has errors (PubSub Topic triggers)

### ISSUE THREAD

**Issue by mattes** [google-github-actions/deploy-cloud-functions#47] opened 2021-02-21 05:30 UTC
<img width="580" alt="Screen Shot 2021-02-20 at 9 28 19 PM" src="https://user-images.githubusercontent.com/1240531/108616496-a0968200-73c2-11eb-91a4-869374dabf5c.png">

I believe I included all required fields. 

Cloud Functions API is enabled and the calling credentials have the `Cloud Functions Admin` and `Service Account User` role.

**Comment by mattes** [comment] 2021-02-21 05:35
From the Logs:
(I replaced sensitive data with `xxx`)

```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "The request has errors"
    },
    "authenticationInfo": {
      "principalEmail": "xxx",
      "serviceAccountKeyName": "xxx"
    },
    "requestMetadata": {
      "callerIp": "xxx",
      "callerSuppliedUserAgent": "github-actions-deploy-cloud-functions/0.1.0 google-api-nodejs-client/4.4.1 (gzip),gzip(gfe),gzip(gfe)",
      "requestAttributes": {
        "time": "2021-02-21T05:23:31.950936Z",
        "auth": {}
      },
      "destinationAttributes": {}
    },
    "serviceName": "cloudfunctions.googleapis.com",
    "methodName": "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction",
    "authorizationInfo": [
      {
        "resource": "xxx",
        "permission": "cloudfunctions.functions.update",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "xxx",
    "request": {
      "function": {
        "name": "xxx",
        "httpsTrigger": {},
        "entryPoint": "Run",
        "sourceUploadUrl": "xxx",
        "runtime": "go113"
      },
      "updateMask": "sourceUploadUrl,name,environmentVariables,entryPoint,runtime,vpcConnector,serviceAccountEmail,timeout,maxInstances,eventTrigger.eventType,eventTrigger.resource,eventTrigger.service",
      "@type": "type.googleapis.com/google.cloud.functions.v1.UpdateFunctionRequest"
    },
    "resourceLocation": {
      "currentLocations": [
        "us-central1"
      ]
    }
  },
  "insertId": "xxx",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "project_id": "xxx",
      "function_name": "xxx"
    }
  },
  "timestamp": "2021-02-21T05:23:31.917344Z",
  "severity": "ERROR",
  "logName": "projects/xxx/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2021-02-21T05:23:32.237789442Z"
}
```

**Comment by bharathkkb** [comment] 2021-02-21 21:31
Thanks for the report @mattes 
If the repo where this occurred is public, could you link it? It would be helpful for repro

**Comment by mattes** [comment] 2021-02-22 00:24
The repo isn't public unfortunately. 

Using `gcloud` I'm able to successfully deploy:

```
	gcloud functions deploy xxx \
		--entry-point Run \
		--runtime go113 \
		--source functions/my-function1 \
		--trigger-topic xxx \
		--project xxx
```

**Comment by mattes** [comment] 2021-02-22 00:33
The difference appears to be `--trigger-topic xxx` from the `gcloud` command. 

Looking at the [API docs](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction), I was able to get my function deployed with:

```
    - name: Deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        region: us-central1
        name: xxx
        runtime: go113
        entry_point: Run
        source_dir: functions/my-function1
        event_trigger_type: google.pubsub.topic.publish
        event_trigger_resource: projects/xxx/topics/xxx
        event_trigger_service: pubsub.googleapis.com
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
```

User error, sorry. :-)

**Comment by mattes** [comment] 2021-02-22 00:48
Actually, my code above doesn't work. See error.

![image](https://user-images.githubusercontent.com/1240531/108644627-a5ac0d80-7464-11eb-931a-72e83bc47193.png)

**Comment by bharathkkb** [comment] 2021-02-22 01:03
@mattes what error does the console show?

**Comment by mattes** [comment] 2021-02-22 02:05
Thanks for helping me with this! 

```
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "Build failed: Build error details not available. Please check the logs at https://console.cloud.google.com/logs/viewer?project=xxxx&advancedFilter=resource.type%3Dbuild%0Aresource.labels.build_id%3Dxxxxfb1%0AlogName%3Dprojects%2Fxxxx%2Flogs%2Fcloudbuild"
    },
    "authenticationInfo": {
      "principalEmail": "xxx"
    },
    "serviceName": "cloudfunctions.googleapis.com",
    "methodName": "google.cloud.functions.v1.CloudFunctionsService.UpdateFunction",
    "resourceName": "xxx"
  },
  "insertId": "xxx",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "project_id": "xxx",
      "function_name": "xxx"
    }
  },
  "timestamp": "2021-02-22T00:47:16.930725Z",
  "severity": "ERROR",
  "logName": "xxx",
  "operation": {
    "id": "xxx",
    "producer": "cloudfunctions.googleapis.com",
    "last": true
  },
  "receiveTimestamp": "2021-02-22T00:47:17.536673731Z"
}
```

I follow the mentioned link:

![image](https://user-images.githubusercontent.com/1240531/108648144-58816900-746f-11eb-8c25-84a14e2b6535.png)

(Replaced some stuff with `xxx`)

**Comment by mattes** [comment] 2021-02-22 02:06
If this error is unrelated from this github action, I'm happy to open support ticket. Please let me know.

**Comment by bharathkkb** [comment] 2021-02-22 04:20
Thanks @mattes 
This seems very similar to the error I got while reproducing https://github.com/google-github-actions/deploy-cloud-functions/issues/41 and a fix is staged here https://github.com/google-github-actions/deploy-cloud-functions/pull/48. Could you try downloading the function source via the console and unzipping it to see if it is corrupted?

**Comment by bharathkkb** [comment] 2021-02-25 03:03
Should be fixed by https://github.com/google-github-actions/deploy-cloud-functions/releases/tag/v0.4.0, feel free to reopen if it still occurs

**Closed by bharathkkb** 2021-02-25 03:03 UTC
Labels: question

**Comment by mattyweb** [comment] 2021-08-21 21:13
> If this error is unrelated from this github action, I'm happy to open support ticket. Please let me know.

Curious if you ever fixed the ZIP file unpacking error described above. I am running into the same problem when trying to deploy a function from Cloud Storage. Works fine when I upload manually or deploy via gcloud.

Looks like a missing application/zip content type problem to me on the Cloud Build side but don't have any confirmation.

Appreciate any help!
