### ISSUE TITLE
Support for trigger_topic in cloud functions?

### ISSUE THREAD

**Issue by samurang87** [google-github-actions/deploy-cloud-functions#5] opened 2020-10-30 12:03 UTC
### Question

Hello!
I see that the [deploy cloud function](https://github.com/google-github-actions/setup-gcloud/tree/master/deploy-cloud-functions#inputs) action there is no `trigger_topic` parameter. Since it's the recommended way to have the cloud function triggered by pub-subs, are you going to add it any time soon? 

I see you're working right now on this, so I didn't want to open a feature request just yet 🙂

**Comment by bharathkkb** [comment] 2020-11-08 00:59
Thanks for the question @samurang87 
For pubsub triggers would this satisfy your usecase?
```
event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
event_trigger_resource: projects/$PROJECT_ID/topics/$TOPIC_ID
```

**Comment by samurang87** [comment] 2020-11-09 11:51
I did try but it failed because I didn't pass the whole path in event_trigger_resource but only the topic id 😅 So I ended up using the setup-gcloud action and then using the cli. I might try it with another cloud function that still hasn't migrated to Github Actions 😉 

Anyway, it would be nice to have support for this parameter, since it's not easy to find about the legacy mode in the documentation 🙂

**Comment by rockevandro** [comment] 2020-12-12 03:52
This works for me:

`
event_trigger_type: google.pubsub.topic.publish
event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/$TOPIC_ID
`

**Comment by thclark** [comment] 2020-12-22 12:02
When you try to add `--trigger-type` (which I just did, assuming it'd be consistent with [the cloud functions api/docs](https://cloud.google.com/functions/docs/tutorials/pubsub#deploying_the_function)), you get:
```
Warning: Unexpected input(s) 'trigger-topic', valid inputs are ['credentials', 'name', 'description', 'project_id', 'region', 'source_dir', 'env_vars', 'entry_point', 'runtime', 'vpc_connector', 'service_account_email', 'timeout', 'max_instances', 'event_trigger_type', 'event_trigger_resource', 'event_trigger_service']
```
So, +1 for either:
- documenting this as a workaround with the `event-types list` (thanks for that, @rockevandro), or
- adding a trigger-type arg, or
- adding a validation that barfs with a suggested workaround and the available event types, instead of the general warning above.

**Comment by highway7** [comment] 2020-12-23 18:49
Thanks @rockevandro , your workaround works for deploying my cf triggered by pub/sub topic as well.

**Comment by bharathkkb** [comment] 2020-12-23 19:11
Thanks for the feedback @thclark @highway7 
To start we should add docs around this, I am bit hesitant to hardcode event types as they may evolve so maybe just adding the gcloud command would be sufficient. 
We can also perform some rudimentary validation that it has to match  `providers/*/eventTypes/*.*` and failing that output the `gcloud functions event-types list` to find available event types. I will do some digging to see if we can get a list of available event-types via API, which would be the cleanest solution.

**Comment by sethvargo** [comment] 2021-12-09 20:57
Even though this was opened first, I'm going to close it as a duplicate of https://github.com/google-github-actions/deploy-cloud-functions/issues/58 which has more discussion. We need to handle trigger inputs better.

**Closed by sethvargo** 2021-12-09 20:57 UTC
Labels: documentation
